server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vishymails/spring-boot-config-repo.git
          search-paths:
           - 'service-config/*service'
          #username: root
          #passphrase: 12345